spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/LOCAPI_DB
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: locapi-group
      auto-offset-reset: earliest

server:
  port: 8090